# Generated by Django 4.2.6 on 2024-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
