# Generated by Django 4.2.6 on 2024-08-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
                ('description', models.TextField()),
                ('gpa', models.CharField(max_length=50)),
            ],
        ),
    ]
