# Generated by Django 4.2.6 on 2024-08-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(default='Yazılım Mühendisi', max_length=100),
            preserve_default=False,
        ),
    ]
