# Generated by Django 4.2.6 on 2024-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_education_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
